version: "3.9"
services:
  db:
    container_name: db
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend-network
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  php:
    container_name: php
    build:
      context: ./php
      secrets:
        - db-password
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/app
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend-network
    depends_on:
      - php
      - db

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
    backend-network:
    frontend-network:
